version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: sudo yarn global add semantic-release
      - run: npm i
      # - run: npm run test-ci
      # - run: npm i codecov
      # - run: ./node_modules/.bin/codecov
      - run: semantic-release

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: deployment
